### ISSUE TITLE
Unraid Template

### ISSUE THREAD

**Issue by thefoxman88** [daya0576/beaverhabits#46] opened 2024-12-24 04:10 UTC
Only change from "basic" template is move from port 3000 to 3010, during start-up I get the following errors.
Beaver-Habit-Tracker.log/

``

The below happens when "Data Storage Method:" is setup to JSON or DATABASE

`text  error  warn  system  array  login  

    async with original_context(app) as maybe_original_state:
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/beaverhabits/main.py", line 23, in lifespan
    await create_db_and_tables()
  File "/app/beaverhabits/app/db.py", line 63, in create_db_and_tables
    async with engine.begin() as conn:
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py", line 1063, in begin
    async with conn:
               ^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/base.py", line 121, in __aenter__
    return await self.start(is_ctxmanager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py", line 273, in start
    await greenlet_spawn(self.sync_engine.connect)
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3278, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 148, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2442, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3302, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 308, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 621, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 352, in connect
    await_only(connection),
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/aiosqlite/core.py", line 140, in _connect
    self._connection = await future
                       ^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/aiosqlite/core.py", line 115, in run
    result = function()
             ^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.12/site-packages/aiosqlite/core.py", line 392, in connector
    return sqlite3.connect(loc, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)

ERROR:    Application startup failed. Exiting.

** Press ANY KEY to close this window ** ``

**Comment by daya0576** [comment] 2024-12-24 06:08
Hi @thefoxman88, thanks for reporting this issue. 

Actually, the custom variables `PUID` & `GUID` are not implemented, so it's not working:
```shell
nobody@2bfabb6afef6:/app$ id nobody 
uid=65534(nobody) gid=65534(nogroup) groups=65534(nogroup)
nobody@2bfabb6afef6:/app$ 
exit
root@Lena:~# id nobody
uid=99(nobody) gid=100(users) groups=100(users),98(nobody)
```

Is it possible to specify the user when launching the unraid app? For example: `-u $(id -u):$(id -g)`

**Comment by deanbirnie** [comment] 2024-12-24 07:28
Yeah doesn't work at all from the unRAID template, I've messed around with PUID and GID with no luck. If anyone gets this up using the unRAID template please post solution.

**Comment by daya0576** [comment] 2024-12-24 08:01
Here is a temporary workaround: 
```
sudo chown -R 65534 /mnt/user/appdata/beaver_habits/
# docker restart
```

I will add the custom variable `PUID` and `PGID` soon.

**Comment by daya0576** [comment] 2024-12-24 08:05
The root cause of this issue: 
- Unraid starts the docker container as nobody
- The process started in the container is nobody too 

However, the uids of these two "nobody" users are different, that's why the process has no permission to create files in host's disk.

**Comment by daya0576** [comment] 2024-12-24 08:19
@nwithan8 Thanks for integrating the app with Unraid. Actually, I just installed Unraid on my PC last night. What a coincidence! :p  

For the permission issue, do u know if it is possible to run the container with `nobody` user? For example: -u $(id -u):$(id -g)

**Comment by deanbirnie** [comment] 2024-12-24 08:29
Can confirm the above workaround works, I have it up and running on unRAID.

**Comment by daya0576** [comment] 2024-12-25 01:43
Closing this issue. 

The permission problem has been resolved by this fix: https://github.com/nwithan8/unraid_templates/pull/53

**Closed by daya0576** 2024-12-25 01:43 UTC
